(define (export-layers src-filename dest-dirname)
    (let* ((image (car (gimp-file-load RUN-NONINTERACTIVE src-filename src-filename)))
            (layers (vector->list (cadr (gimp-image-get-layers image)))))
        (for-each (lambda (layer)
            (begin (gimp-layer-flatten layer)
            (let* ((layer-name (car (gimp-item-get-name layer)))
                    (dest-filename (apply string-append (list dest-dirname "/" layer-name ".png"))))
            (file-png-save RUN-NONINTERACTIVE image layer dest-filename dest-filename 0 9 1 0 0 0 0)
        ))) layers)
    ))
